In [65]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv('googleplaystore.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [82]:
# adapted and borrowed from here:
# https://stackoverflow.com/questions/42865724/python-parse-human-readable-filesizes-into-bytes/42865957

def parseSize(size):
    if size == 'Varies with device':
        return np.NAN
    elif type(size) is not str:
        return np.NAN
    
    size_characters = []
    for letter in size:
        if letter.lower() in ('k','m','g','t'):
            size_characters.append(' ')
        size_characters.append(letter)
    size = ''.join(size_characters)
    
    try:
        if len(size.split()) != 2:
            return np.NAN
    except:
        print(size)
        print(type(size))

    
    units = {"B": 1, "K": 10**3, "M": 10**6, "G": 10**9, "T": 10**12,
            "B": 1, "k": 10**3, "m": 10**6, "g": 10**9, "t": 10**12}

    
    number, unit = [string.strip() for string in size.split()]
    return int(float(number)*units[unit])

Testing it out...

In [68]:
example_strings = ["10.43K", "11G", "343.1M",'Varies with device']

for example_string in example_strings:
    print(parseSize(example_string))

10430
11000000000
343100000
nan

## Let's Create a new column
### using parseSize() function
### and, diviting by 10**6 (to convert to MB, instead of bytes)

In [71]:
df['Size_in_MB'] = df.Size.apply(parseSize)/10**6

## Check results:

In [79]:
df[['Size','Size_in_MB']].head(50)

                  Size  Size_in_MB
0                  19M        19.0
1                  14M        14.0
2                 8.7M         8.7
3                  25M        25.0
4                 2.8M         2.8
5                 5.6M         5.6
6                  19M        19.0
7                  29M        29.0
8                  33M        33.0
9                 3.1M         3.1
10                 28M        28.0
11                 12M        12.0
12                 20M        20.0
13                 21M        21.0
14                 37M        37.0
15                2.7M         2.7
16                5.5M         5.5
17                 17M        17.0
18                 39M        39.0
19                 31M        31.0
20                 14M        14.0
21                 12M        12.0
22                4.2M         4.2
23                7.0M         7.0
24                 23M        23.0
25                6.0M         6.0
26                 25M        25.0
27                6.1M         6.1
28                4.6M         4.6
29                4.2M         4.2
30                9.2M         9.2
31                5.2M         5.2
32                 11M        11.0
33                 11M        11.0
34                4.2M         4.2
35                9.2M         9.2
36                 24M        24.0
37  Varies with device         NaN
38                 11M        11.0
39                9.4M         9.4
40                 15M        15.0
41                 10M        10.0
42  Varies with device         NaN
43                1.2M         1.2
44                 12M        12.0
45                 24M        24.0
46                 26M        26.0
47                8.0M         8.0
48                7.9M         7.9
49                 25M        25.0

## Check for examples in kilobytes:

In [80]:
df[df.Size.str.contains('k')][['Size','Size_in_MB']].head(10)

      Size  Size_in_MB
58    201k       0.201
209    23k       0.023
384    79k       0.079
450   118k       0.118
458   695k       0.695
479    18k       0.018
768   556k       0.556
775   526k       0.526
1019  334k       0.334
1521  232k       0.232

## Check column types
Note: new column is a float

and, non-values stored as NA's

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 14 columns):
App               10841 non-null object
Category          10841 non-null object
Rating            9367 non-null float64
Reviews           10841 non-null object
Size              10841 non-null object
Installs          10841 non-null object
Type              10840 non-null object
Price             10841 non-null object
Content Rating    10840 non-null object
Genres            10841 non-null object
Last Updated      10841 non-null object
Current Ver       10833 non-null object
Android Ver       10838 non-null object
Size_in_MB        9145 non-null float64
dtypes: float64(2), object(12)
memory usage: 1.2+ MB